spring:
  data:
    mongodb:
      #host: localhost
      #port: 27017
      username: admin
      password: compasso123
      enabled: true
      database: sistema
      uri: mongodb://localhost:27017/sistema

server:
  port: 8080

logging:
  level:
    io.sicredi.precificacao.credito: DEBUG



